# Generated by Django 3.0.8 on 2020-07-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=64)),
                ('listing_description', models.CharField(max_length=256)),
                ('starting_bid', models.FloatField()),
                ('url_listing_image', models.CharField(blank=True, max_length=128)),
                ('listing_category', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
