# Generated by Django 3.0.8 on 2020-07-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlistings',
            name='url_listing_image',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
