# Generated by Django 3.0.8 on 2020-07-16 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200716_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionlistings',
            old_name='starting_bid',
            new_name='bid',
        ),
    ]
