# Generated by Django 3.0.8 on 2020-07-17 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20200716_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='post date'),
        ),
    ]
