# Generated by Django 3.0.8 on 2020-07-17 23:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctionlistings_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlistings',
            name='users_whatching',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
