# Generated by Django 3.0.8 on 2020-07-20 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auctionlistings_users_whatching'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('bid_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bid', to=settings.AUTH_USER_MODEL)),
                ('listing_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_bid', to='auctions.AuctionListings')),
            ],
        ),
    ]
